apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: chatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000